spring.application.name=skirental

logging.level.nl.miwnn=DEBUG
logging.level.org.springframework=WARN

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
