DROP DATABASE IF EXISTS skirental;
CREATE DATABASE skirental;
CREATE USER IF NOT EXISTS 'userSki'@'localhost'
IDENTIFIED BY 'userSkiPW';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, INDEX, REFERENCES ON skirental.*
    TO 'userSki'@'localhost';
FLUSH PRIVILEGES